name: pomodoro_timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  circular_countdown_timer: ^0.2.4
  get: ^4.7.2
  mobile_scanner: ^7.0.1
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  geolocator: ^10.1.0  # 위치 정보
  geocoding: ^2.1.1  # 지오코딩
  intl: ^0.19.0  # 날짜/시간 포맷팅
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600

